version: "3.9"
services:
  users_db:
    image: postgres:latest
    container_name: users_db
    environment:
      POSTGRES_USER: app_user
      POSTGRES_PASSWORD: secure_password
      POSTGRES_DB: users_db
    ports:
      - "5433:5432"

  products_db:
    image: postgres:latest
    container_name: products_db
    environment:
      POSTGRES_USER: app_user
      POSTGRES_PASSWORD: secure_password
      POSTGRES_DB: products_db
    ports:
      - "5434:5432"

  users_service:
    build:
      context: ./users_service
    container_name: users_service
    ports:
      - "8001:8001"
    depends_on:
      - users_db
    environment:
      DATABASE_URL: "postgresql://app_user:secure_password@users_db:5432/users_db"

  products_service:
    build:
      context: ./products_service
    container_name: products_service
    ports:
      - "8002:8002"
    depends_on:
      - products_db
    environment:
      DATABASE_URL: "postgresql://app_user:secure_password@products_db:5432/products_db"

volumes:
  postgres_data_users:
  postgres_data_products:
