version: "3.9"
services:
  redis:
    image: redis:alpine
    container_name: redis
    ports:
      - "6379:6379"

  producer_service:
    build:
      context: ./producer_service
    container_name: producer_service
    ports:
      - "8001:8001"
    depends_on:
      - redis

  consumer_service:
    build:
      context: ./consumer_service
    container_name: consumer_service
    ports:
      - "8002:8002"
    depends_on:
      - redis
