version: "3.9"

services:
  layered_app:
    build:
      context: .
    container_name: layered_app
    ports:
      - "8000:8000"
    depends_on:
      - layered_db
    environment:
      DATABASE_URL: "postgresql://app_user:secure_password@layered_db:5432/task_db"

  layered_db:
    image: postgres:latest
    container_name: layered_db
    environment:
      POSTGRES_USER: app_user
      POSTGRES_PASSWORD: secure_password
      POSTGRES_DB: task_db
    ports:
      - "5432:5432"
